//------------------------------------------------------------------------------
// <auto-generated>
//     This content is updated by `generate-assembly-info.sh`.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("0.15.630.1108")]
[assembly: AssemblyFileVersion("0.15.630.1108")]
[assembly: AssemblyInformationalVersion("0.15.630.1108-commitHashPlaceholder-commitBranchPlaceholder")]
